### ISSUE TITLE
Shutdown hawkBit sandbox

### ISSUE THREAD

**Issue by avgustinmm** [eclipse-hawkbit/hawkbit#1700]
Since the last 0.5.0 release of hawkBit is without UI, the current sandbox points out to the Swagger UI. 
It has no value as a demo / hands-on shandbox. So, the sandbox shall be shut down.

**Comment by strailov** [comment]
Yes this seems reasonable. After removing the vaadin UI there is no point keeping the sandbox.

**Comment by diegorondini** [comment]
Hi,

I think it still makes sense to have the sandbox, as it showcases what hawkBit provides without having to spin up a container or a set of containers.
It's still very useful for testing DDI API and for exploring the Management API, since the Swagger UI now provides a convenient UI to test Mgmt API.

Hara uses the sandbox as its default in the virtual device:
https://github.com/eclipse-hara/hara-ddiclient/blob/master/virtual-device/src/main/kotlin/org/eclipse/hara/ddiclient/virtualdevice/Configuration.kt#L33C35-L33C69
https://github.com/eclipse-hara/hara-ddiclient/tree/master?tab=readme-ov-file#build-from-source

So if you're asking whether it's still useful without the Vaadin UI, it is.

Regards

**Comment by avgustinmm** [comment]
@diegorondini, @strailov, all,

there is a new development regarding the sandbox. I (and all hawkbit-dev list) received an email on behalf of Eclipse Webmaster regarding project virtual servers. It states:
```quote
Starting in Q1 2025, we are requiring that all projects that have a virtual server hosted by or sponsored by 
the Foundation submit and maintain an update schedule.  This schedule should indicate who on the project 
team is responsible for managing the server, and establish a consistent update cadence for both software 
and the OS that your project will follow.

Members of the project that are identified as responsible will also be added to our GDPR notices if they do 
not already receive them, so they can action any GDPR requests the Foundation receives.

If the project doesn’t have anyone that is willing to take on such responsibilities, we should begin discussing 
the graceful shutdown of your project virtual server.

Please submit your schedule to ... by February 17, 2025 or engage with the Security or Infra(...) teams via 
email by that time.  If we don’t hear from you by the due date, we’ll file an issue to schedule the shutdown, 
after which your data will be held briefly before it is removed.
``` 
This means that if no volunteer is available to take responsibility for the hawkBit virtual server the sandbox runs on, we shall shut down the sandbox anyway.

Regarding the usefulness:
* Swagger UI is something that could be useful for tests or demos by very in-depth with hawkBit users which could easily start its own hawkBit instance
* probably Eclipse hara shall use as default URL http://localhost:8080 - pointing out directly to an URL somewhere out in internet, in my opinion, is a security vulnerability anyway.

**Comment by avgustinmm** [comment]
Virtual machines are shut down by the Eclipse Foundation infrastructure team.
The correspondent code is removed from hawkBit project.

**Comment by diegorondini** [comment]
@avgustinmm thanks for the heads-up.

Hara now no longer references the sandbox:
https://github.com/eclipse-hara/hara-ddiclient/pull/56

**Comment by diegorondini** [comment]
@avgustinmm @strailov Can you update the hawkBit dockerhub page? It still references the sandbox:
https://hub.docker.com/r/hawkbit/hawkbit-update-server#hawkbit-sandbox
