### ISSUE TITLE
Update target without a Rollout

### ISSUE THREAD

**Issue by FabioPetry18** [eclipse-hawkbit/hawkbit#2007]
I want to know which process is called by the api in this interface I tried 

![image](https://github.com/user-attachments/assets/a2bf4885-391c-4a49-a347-8b4788023c6a)

/rest/v1/targets/{targetid}/assignedDS

/rest/v1/distributionsets/1/assignedTargets

and they both returned
{
    "exceptionClass": "org.eclipse.hawkbit.repository.exception.MultiAssignmentIsNotEnabledException",
    "errorCode": "hawkbit.server.error.multiassignmentNotEnabled",
    "message": "The requested operation requires multiple assignments to be enabled."
}

but in the UI its works!

**Comment by avgustinmm** [comment]
Which version of hawbit you are using?
This UI is not supported since at least last 2 releases.
This UI works directly with DB so it's not clear that in these old hawkbit versions there is rest alternative.
Anyway, from the exception, I guess that maybe in your payload you put "weight", which in old hawkbit requires multiassigment enabled.
Try to remove "weight" from your payload
